// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  Sidebar: [{ type: "autogenerated", dirName: "." }],
  community: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
