---
blank_issues_enabled: false
contact_links:
  - name: Z-Shell Zi Community Support
    url: https://github.com/z-shell/zi/discussions
    about: Please ask and answer questions here.
  - name: Z-Shell Zi Wiki Pages
    url: https://github.com/z-shell/z-shell.pages.dev/discussions
    about: Please ask and answer questions about documentation here.
